# Generated by Django 6.0.6 on 2026-06-17 10:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(max_length=120)),
                ('service_required', models.CharField(choices=[('aluminum_window', 'Aluminum Window'), ('aluminum_door', 'Aluminum Door'), ('aluminum_partition', 'Aluminum Partition'), ('aluminum_frame', 'Aluminum Frame'), ('aluminum_rack', 'Aluminum Rack'), ('wooden_bed', 'Wooden Bed'), ('sofa', 'Sofa'), ('table', 'Table'), ('chair', 'Chair'), ('wardrobe', 'Wardrobe'), ('kitchen_cabinet', 'Kitchen Cabinet'), ('office_furniture', 'Office Furniture'), ('custom_design', 'Custom Design')], max_length=40)),
                ('message', models.TextField(blank=True)),
                ('preferred_contact', models.CharField(choices=[('call', 'Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='call', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Public enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('site_supervisor', 'Site Supervisor'), ('billing', 'Billing'), ('support', 'Support')], default='support', max_length=30)),
                ('whatsapp_enabled', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('show_on_website', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='payment_qr',
            field=models.FileField(blank=True, upload_to='business/payments/'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='service_area',
            field=models.CharField(default='All India service available', max_length=180),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='show_payment_details',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='tagline',
            field=models.CharField(default='Furniture, aluminum, glass and custom interior work across India.', max_length=220),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='upi_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Income / Received'), ('expense', 'Expense / Paid')], max_length=20)),
                ('category', models.CharField(choices=[('customer_payment', 'Customer Payment'), ('advance', 'Advance'), ('worker_wage', 'Worker Wage'), ('material_purchase', 'Material Purchase'), ('supplier_payment', 'Supplier Payment'), ('refund', 'Refund'), ('transport', 'Transport'), ('rent', 'Rent'), ('electricity', 'Electricity'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=140)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('online_gateway', 'Online Gateway')], max_length=30)),
                ('transaction_date', models.DateField(default=django.utils.timezone.localdate)),
                ('party_name', models.CharField(blank=True, max_length=120)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('attachment', models.FileField(blank=True, upload_to='transactions/')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.order')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.worker')),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
            },
        ),
    ]
